baseURL: https://belajarkonversi.com
languageCode: id-ID
title: Belajar Konversi | Optimasi Conversion Rate Situs Kamu

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
paginate: 5

googleAnalytics: G-SGEE08XR7D
disqusShortname: belajarkonversi

minify:
    disableXML: true
    minifyOutput: true

markup :
    goldmark :
        renderer :
            unsafe : true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Belajar Konversi | Optimasi Conversion Rate Situs Kamu
    description: "Dengan teknik conversion rate optimization, kamu akan meningkatkan tingkat konversi situs Anda sehingga meningkatkan pendapatan bisnis Anda."
    keywords: [Blog, Portfolio, PaperMod]
    author: Dimas Ibrahim
    # author: ["Me", "You"] # multiple authors
    images: ["https://belajarkonversi.com/images/bktumnail.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://belajarkonversi.com/images/bk.ico"
        favicon16x16: "https://belajarkonversi.com/images/bk16.ico"
        favicon32x32: "https://belajarkonversi.com/images/bk.ico"
        apple_touch_icon: "https://belajarkonversi.com/images/bk.ico"
        safari_pinned_tab: "https://belajarkonversi.com/images/bk.ico"

    label:
        text: "BelajarKonversi"
        icon: 
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Konversikan Pengunjung Menjadi Konsumen"
        Content: 

    socialIcons:
        - name: twitter
          url: "https://twitter.com/"
        - name: stackoverflow
          url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/"

    analytics:
        google:
            SiteVerificationTag: "G-SGEE08XR7D"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/<path_to_repo>/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Dukung Penulis
          name: Dukung Penulis
          url: https://sociabuzz.com/belajarkonversi/donate
          weight: 30


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai